services:
  - type: web
    name: workforce-manager-simplified
    env: node
    plan: free
    buildCommand: bash ./render-deploy.sh
    startCommand: npm run start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: da_vittorino_workforce_manager_secret_key_2024
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 