services:
  - type: web
    name: workforce-manager-backend
    env: node
    plan: free
    buildCommand: bash ./render-build.sh
    startCommand: npm run start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
    healthCheckPath: /api/auth/me
    autoDeploy: true 